Fixes PHP error when trying to delete an index
Error: Call to undefined method SearchApiIndex::hasStatus()
in search_api_admin_confirm() (line 2344 of /modules/search_api/search_api.admin.inc).

D7 Entity object had a method hasStatus() and backdrop core entity module
no longer contains this method but we still need it.

Source: https://git.drupalcode.org/project/entity/-/blob/7.x-1.x/includes/entity.inc
line 83